spring.application.name=InboxIQ

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/inboxiq
spring.datasource.username=postgres
spring.datasource.password=vs@1707
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
